#pragma once

typedef void(*BlendShapePosBatchFn)(
    void *pool,
    const uint32_t *morph_offsets,
    const uint32_t *morph_block_starts,
    const uint32_t *v_indices,
    const float *deltas_pos,
    const float *weights,
    float       *last_weights,
    float       *delta_weights,
    uint32_t    *active_buf,
    const float *base_verts,
    float       *out_verts,
    uint32_t vertex_count,
    uint32_t morph_count,
    uint32_t batch_size);

extern "C" void BlendShapePosApplyBatchSSE4(
    void *pool,
    const uint32_t *morph_offsets,
    const uint32_t *morph_block_starts,
    const uint32_t *v_indices,
    const float *deltas_pos,
    const float *weights,
    float       *last_weights,
    float       *delta_weights,
    uint32_t    *active_buf,
    const float *base_verts,
    float       *out_verts,
    uint32_t vertex_count,
    uint32_t morph_count,
    uint32_t batch_size);

extern "C" void BlendShapePosApplyBatchAVX2FMA(
    void *pool,
    const uint32_t *morph_offsets,
    const uint32_t *morph_block_starts,
    const uint32_t *v_indices,
    const float *deltas_pos,
    const float *weights,
    float       *last_weights,
    float       *delta_weights,
    uint32_t    *active_buf,
    const float *base_verts,
    float       *out_verts,
    uint32_t vertex_count,
    uint32_t morph_count,
    uint32_t batch_size);

typedef void(*BlendShapePosNormBatchFn)(
    void *pool,
    const uint32_t *morph_offsets,
    const uint32_t *morph_block_starts,
    const uint32_t *v_indices,
    const float *deltas_pos,
    const float *deltas_norm,
    const float *weights,
    float       *last_weights_pos,
    float       *last_weights_pos_norm,
    float       *delta_weights,
    uint32_t    *active_buf,
    const float *base_verts,
    const float *base_norms,
    float       *out_verts,
    float       *out_norms,
    uint32_t vertex_count,
    uint32_t morph_count,
    uint32_t batch_size);

extern "C" void BlendShapePosNormApplyBatchSSE4(
    void *pool,
    const uint32_t *morph_offsets,
    const uint32_t *morph_block_starts,
    const uint32_t *v_indices,
    const float *deltas_pos,
    const float *deltas_norm,
    const float *weights,
    float       *last_weights_pos,
    float       *last_weights_pos_norm,
    float       *delta_weights,
    uint32_t    *active_buf,
    const float *base_verts,
    const float *base_norms,
    float       *out_verts,
    float       *out_norms,
    uint32_t vertex_count,
    uint32_t morph_count,
    uint32_t batch_size);

extern "C" void BlendShapePosNormApplyBatchAVX2FMA(
    void *pool,
    const uint32_t *morph_offsets,
    const uint32_t *morph_block_starts,
    const uint32_t *v_indices,
    const float *deltas_pos,
    const float *deltas_norm,
    const float *weights,
    float       *last_weights_pos,
    float       *last_weights_pos_norm,
    float       *delta_weights,
    uint32_t    *active_buf,
    const float *base_verts,
    const float *base_norms,
    float       *out_verts,
    float       *out_norms,
    uint32_t vertex_count,
    uint32_t morph_count,
    uint32_t batch_size);

extern "C" __declspec(dllexport) void BlendShapePosBatch(
    void *pool,
    const uint32_t *morph_offsets,
    const uint32_t *morph_block_starts,
    const uint32_t *v_indices,
    const float *deltas_pos,
    const float *weights,
    float       *last_weights,
    float       *delta_weights,
    uint32_t    *active_buf,
    const float *base_verts,
    float       *out_verts,
    uint32_t vertex_count,
    uint32_t morph_count,
    uint32_t batch_size);

extern "C" __declspec(dllexport) void BlendShapePosNormBatch(
    void *pool,
    const uint32_t *morph_offsets,
    const uint32_t *morph_block_starts,
    const uint32_t *v_indices,
    const float *deltas_pos,
    const float *deltas_norm,
    const float *weights,
    float       *last_weights_pos,
    float       *last_weights_pos_norm,
    float       *delta_weights,
    uint32_t    *active_buf,
    const float *base_verts,
    const float *base_norms,
    float       *out_verts,
    float       *out_norms,
    uint32_t vertex_count,
    uint32_t morph_count,
    uint32_t batch_size);
